const genreSeeds = {
  genres: [
    "acoustic",
    "afrobeat",
    "alt-rock",
    "alternative",
    "ambient",
    "anime",
    "black-metal",
    "bluegrass",
    "blues",
    "bossanova",
    "brazil",
    "breakbeat",
    "british",
    "cantopop",
    "chicago-house",
    "children",
    "chill",
    "classical",
    "club",
    "comedy",
    "country",
    "dance",
    "dancehall",
    "death-metal",
    "deep-house",
    "detroit-techno",
    "disco",
    "disney",
    "drum-and-bass",
    "dub",
    "dubstep",
    "edm",
    "electro",
    "electronic",
    "emo",
    "folk",
    "forro",
    "french",
    "funk",
    "garage",
    "german",
    "gospel",
    "goth",
    "grindcore",
    "groove",
    "grunge",
    "guitar",
    "happy",
    "hard-rock",
    "hardcore",
    "hardstyle",
    "heavy-metal",
    "hip-hop",
    "holidays",
    "honky-tonk",
    "house",
    "idm",
    "indian",
    "indie",
    "indie-pop",
    "industrial",
    "iranian",
    "j-dance",
    "j-idol",
    "j-pop",
    "j-rock",
    "jazz",
    "k-pop",
    "kids",
    "latin",
    "latino",
    "malay",
    "mandopop",
    "metal",
    "metal-misc",
    "metalcore",
    "minimal-techno",
    "movies",
    "mpb",
    "new-age",
    "new-release",
    "opera",
    "pagode",
    "party",
    "philippines-opm",
    "piano",
    "pop",
    "pop-film",
    "post-dubstep",
    "power-pop",
    "progressive-house",
    "psych-rock",
    "punk",
    "punk-rock",
    "r-n-b",
    "rainy-day",
    "reggae",
    "reggaeton",
    "road-trip",
    "rock",
    "rock-n-roll",
    "rockabilly",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "singer-songwriter",
    "ska",
    "sleep",
    "songwriter",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "synth-pop",
    "tango",
    "techno",
    "trance",
    "trip-hop",
    "turkish",
    "work-out",
    "world-music",
  ],
};

/////////////////////////////////////////////////////////////////////

const genres = [
  "acoustic",
  "afrobeat",
  "alternative",
  "ambient",
  "bluegrass",
  "blues",
  "bossanova",
  "brazil",
  "breakbeat",
  "cantopop",
  "chill",
  "club",
  "country",
  "dance",
  "dancehall",
  "death-metal",
  "deep-house",
  "disco",
  "drum-and-bass",
  "dubstep",
  "edm",
  "electronic",
  "emo",
  "folk",
  "funk",
  "garage",
  "goth",
  "grindcore",
  "groove",
  "grunge",
  "hardcore",
  "heavy-metal",
  "hip-hop",
  "house",
  "idm",
  "indie",
  "industrial",
  "j-pop",
  "jazz",
  "k-pop",
  "latin",
  "metal",
  "mpb",
  "new-age",
  "pop",
  "power-pop",
  "progressive-house",
  "psych-rock",
  "punk",
  "r-n-b",
  "reggae",
  "singer-songwriter",
  "ska",
  "soul",
  "synth-pop",
  "techno",
  "trance",
  "trip-hop",
];

/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
const randomizeGenreSeeds = (arr) => {
  // returns 5 random, non-repeating items from arr in a new array
  const b = arr.slice();
  const temp = [];

  for (let i = 0; i < 5; i++) {
    let arr = b[Math.floor(Math.random() * b.length)];
    let index = b.indexOf(arr);
    b.splice(index, 1);
    temp.push(arr);
  }
  return temp.join(",");
};

console.log(randomizeGenreSeeds(genres));
/////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
// curl -X "GET" "https://api.spotify.com/v1/recommendations?market=US&seed_genres=country%2Cdeep-house%2Ctrance%2Cmetal%2Cr-n-b&target_key=4&min_popularity=50" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQBSpuPhEQtLuDnVLh0l1M6pCNwg8me6-vybnBEs43YLgNWkN9zt4j8UOneEsRmm_85-51eASQ7NeUiyw325PrpS-UeEpevcBh0GkTU8zomZQphp5ltwQ89mQym0Mgy7ljPdWaYeWm0AUr6oGSA8n9nZWLH4"

//   GET https://api.spotify.com/v1/recommendations
